class OrderEntity {
  static ORDER_STATUS = {
    OPEN: 'OPEN',
    CANCELLED: 'CANCELLED',
    PROCESSING: 'PROCESSING',
    CAPTURED_PAYMENT: 'CAPTURED_PAYMENT',
    CREATED_FULFILLMENT: 'CREATED_FULFILLMENT',
    PARTIAL_FULFILLMENT: 'PARTIAL_FULFILLMENT',
    CREATED_SHIPMENT_LABEL: 'CREATED_SHIPMENT_LABEL',
    READY_FOR_PICKUP: 'READY_FOR_PICKUP',
    PACKED: 'PACKED',
    PICKED: 'PICKED',
    BEING_DELIVERED: 'BEING_DELIVERED',
    SENT: 'SENT',
    CLOSED: 'CLOSED',
    PARTIALLY_REFUNDED: 'PARTIALLY_REFUNDED',
    REFUNDED: 'REFUNDED'
  };

}

module.exports = OrderEntity;
